# Carestream MCP Bridge — unified installer (x-ray SERVER + consultation CLIENT).
# Detects reachable SCAN shares and installed Carestream apps, writes per-PC config,
# then installs the bridge via install-xray-bridge.ps1.
param(
    [string]$InstallPath = "C:\BananaBridge-Carestream-MCP",
    [int]$Port = 17890,
    [string]$BananaWebPath = "",
    [switch]$NoAutoStart,
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "    OK: $msg" -ForegroundColor Green }
function Write-Warn2($msg) { Write-Host "    WARNING: $msg" -ForegroundColor Yellow }

function Test-PathSafe($Path) {
    if ([string]::IsNullOrWhiteSpace($Path)) { return $false }
    try { return Test-Path -LiteralPath $Path } catch { return $false }
}

function Get-CarestreamScanRootCandidates {
    $list = New-Object System.Collections.Generic.List[string]
    foreach ($local in @("C:\Image\SCAN", "C:\IMAGE\SCAN")) { [void]$list.Add($local) }
    $hosts = New-Object System.Collections.Generic.List[string]
    if ($env:COMPUTERNAME) { [void]$hosts.Add($env:COMPUTERNAME) }
    foreach ($h in @(
        "RECEPTION_MCP", "RECEPTION", "RECEPTION_TKO", "RECEPTION_PL",
        "RECEPTION_CWB", "RECEPTION_QB", "RECEPTION_MK", "CSMAIN"
    )) { [void]$hosts.Add($h) }
    try {
        $net = (net view 2>$null)
        foreach ($line in $net) {
            if ($line -match '\\\\(RECEPTION\S*|CSMAIN)\b') {
                [void]$hosts.Add($Matches[1].Trim())
            }
        }
    } catch {}
    $seen = @{}
    foreach ($h in $hosts) {
        $key = $h.ToUpperInvariant()
        if ($seen.ContainsKey($key)) { continue }
        $seen[$key] = $true
        foreach ($suf in @("IMAGE\SCAN", "IMAGE\Scan")) {
            [void]$list.Add(("\\" + $h + "\" + $suf))
        }
    }
    return @($list)
}

function Get-ReachableScanRoots {
    $found = New-Object System.Collections.Generic.List[string]
    foreach ($root in (Get-CarestreamScanRootCandidates)) {
        if (Test-PathSafe $root) { [void]$found.Add($root) }
    }
    if ($found.Count -eq 0) {
        return @("\\RECEPTION_MCP\IMAGE\SCAN", "\\CSMAIN\IMAGE\Scan")
    }
    return @($found)
}

function Test-CarestreamTwInstalled {
    foreach ($p in @(
        "C:\Program Files (x86)\Carestream\CSImaging\TW.exe",
        "C:\Program Files\Carestream\CSImaging\TW.exe"
    )) {
        if (Test-PathSafe $p) { return $true }
    }
    return $false
}

function Test-CarestreamPatientInstalled {
    foreach ($p in @(
        "C:\Program Files (x86)\Carestream\Patient Browser\Patient.exe",
        "C:\Program Files\Carestream\Patient Browser\Patient.exe"
    )) {
        if (Test-PathSafe $p) { return $true }
    }
    return $false
}

function Get-CarestreamPcProfile {
    $roots = Get-ReachableScanRoots
    $tw = Test-CarestreamTwInstalled
    $patient = Test-CarestreamPatientInstalled
    $hasReception = ($roots | Where-Object { $_ -match 'RECEPTION' }).Count -gt 0
    $hasCsmain = ($roots | Where-Object { $_ -match 'CSMAIN' }).Count -gt 0

    $role = "consultation-client"
    if ($tw -and $hasReception) { $role = "xray-server" }
    elseif ($tw -and -not $hasCsmain) { $role = "xray-server" }
    elseif ($hasReception -and -not $hasCsmain) { $role = "xray-server" }

    $primary = $roots[0]
    return [ordered]@{
        role = $role
        hostname = $env:COMPUTERNAME
        scan_roots = $roots
        primary_scan_root = $primary
        tw_installed = $tw
        patient_installed = $patient
    }
}

function Write-LauncherConfigFile($Path, $Profile) {
    $lines = New-Object System.Collections.Generic.List[string]
    [void]$lines.Add("# Auto-generated by Carestream MCP Bridge installer - $(Get-Date -Format 'yyyy-MM-dd HH:mm')")
    [void]$lines.Add("# PC role: $($Profile.role) on $($Profile.hostname)")
    [void]$lines.Add('$script:NntScanRootsOverride = @(')
    $roots = @($Profile.scan_roots)
    for ($i = 0; $i -lt $roots.Count; $i++) {
        # PowerShell 5.1 rejects a trailing comma after the last array element.
        $suffix = if ($i -lt ($roots.Count - 1)) { ',' } else { '' }
        [void]$lines.Add("    `"$($roots[$i])`"$suffix")
    }
    [void]$lines.Add(')')
    [void]$lines.Add("`$script:CarestreamBridgeRole = `"$($Profile.role)`"")
    [void]$lines.Add("`$script:CarestreamBridgeHostname = `"$($Profile.hostname)`"")
    Set-Content -LiteralPath $Path -Value ($lines -join "`r`n") -Encoding UTF8
}

function ConvertTo-JsPathLiteral([string]$Path) {
    if ([string]::IsNullOrWhiteSpace($Path)) { return '' }
    return ($Path.Replace('\', '\\'))
}

function Write-BananaPcConfigFile($Path, $Profile) {
    $rootJs = ConvertTo-JsPathLiteral $Profile.primary_scan_root
    $lines = @(
        '/**',
        ' * Auto-generated by Carestream MCP Bridge installer.',
        " * PC: $($Profile.hostname)  Role: $($Profile.role)",
        ' * Copy this file to your Banana web app folder as xray-pc-config.js',
        ' */',
        '(function () {',
        "  window.XRAY_PC_ROLE = '$($Profile.role)';",
        "  window.XRAY_PC_HOSTNAME = '$($Profile.hostname)';",
        "  window.XRAY_TROPHY_SCAN_ROOT = '$rootJs';",
        "  window.XRAY_TROPHY_SUB_PATTERN = '{patient_no}';",
        "  window.CLINIC_IMAGE_ROOT = 'C:\\\\Image';",
        "  window.XRAY_LAUNCHER_PORTS = [17891, 17890];",
        "  window.XRAY_LAUNCHER_HOSTS = ['127.0.0.1', 'localhost'];",
        '})();',
        ''
    )
    Set-Content -LiteralPath $Path -Value ($lines -join "`r`n") -Encoding UTF8
}

function Write-InstallNotesFile($Path, $Profile) {
    $roots = ($Profile.scan_roots -join "`r`n  - ")
    $notes = @"
Joyful Smile — Carestream MCP Bridge
=====================================
Installed: $(Get-Date -Format 'yyyy-MM-dd HH:mm')
Computer:  $($Profile.hostname)
Role:      $($Profile.role)

Carestream Patient.exe: $(if ($Profile.patient_installed) { 'found' } else { 'NOT found — Carestream button may not work' })
Trophy TW.exe:        $(if ($Profile.tw_installed) { 'found' } else { 'NOT found — Trophy only works on MCP/server PCs with CSImaging' })

SCAN roots configured for this PC:
  - $roots

Bridge URL: http://127.0.0.1:$Port/status

Banana web app:
  1. Copy xray-pc-config.js from this folder into your Banana web app root
     (same folder as index.html), OR merge settings into existing xray-pc-config.js
  2. Open http://127.0.0.1:5500/index.html (not file:// or GitHub Pages)
  3. Hard refresh Ctrl+F5

Server PC (xray-server): Trophy + Carestream — TW.exe opens SCAN folder on RECEPTION_MCP
Client PC (consultation-client): Carestream Patient Browser; Trophy if TW.exe is installed
"@
    Set-Content -LiteralPath $Path -Value $notes -Encoding UTF8
}

function Copy-HelperScripts($InstallPath) {
    $helpers = @(
        "Start Carestream MCP Launcher.bat",
        "Test Carestream MCP Launcher.bat"
    )
    foreach ($name in $helpers) {
        $src = Join-Path $scriptDir $name
        if (Test-PathSafe $src) {
            Copy-Item -LiteralPath $src -Destination (Join-Path $InstallPath $name) -Force
        }
    }
}

if ($Uninstall) {
    & powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $scriptDir "install-xray-bridge.ps1") `
        -InstallPath $InstallPath -Port $Port -Uninstall `
        -ShortcutName "Joyful Smile Carestream MCP Bridge.lnk" `
        -EnabledSystems "carestream","trophy"
    exit $LASTEXITCODE
}

Write-Host ""
Write-Host "Joyful Smile Carestream MCP Bridge — unified installer" -ForegroundColor Green
Write-Host "(Works on x-ray SERVER and consultation CLIENT PCs)" -ForegroundColor Green
Write-Host ""

Write-Step "Detecting this PC (Carestream apps + SCAN shares)"
$profile = Get-CarestreamPcProfile
Write-Ok "Role: $($profile.role) on $($profile.hostname)"
Write-Ok "Primary SCAN root: $($profile.primary_scan_root)"
Write-Host "    Reachable roots: $($profile.scan_roots -join ', ')"
Write-Host "    Patient.exe: $(if ($profile.patient_installed) { 'yes' } else { 'no' })  TW.exe: $(if ($profile.tw_installed) { 'yes' } else { 'no' })"

Write-Step "Installing bridge to $InstallPath"
$bridgeArgs = @(
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", (Join-Path $scriptDir "install-xray-bridge.ps1"),
    "-InstallPath", $InstallPath,
    "-Port", $Port,
    "-ShortcutName", "Joyful Smile Carestream MCP Bridge.lnk",
    "-EnabledSystems", "carestream", "trophy"
)
if ($NoAutoStart) { $bridgeArgs += "-NoAutoStart" }
& powershell @bridgeArgs
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

Write-Step "Writing per-PC configuration"
$configPs1 = Join-Path $InstallPath "xray-launcher-config.ps1"
$configJs  = Join-Path $InstallPath "xray-pc-config.js"
$notesTxt  = Join-Path $InstallPath "INSTALL-NOTES.txt"
Write-LauncherConfigFile $configPs1 $profile
Write-BananaPcConfigFile $configJs $profile
Write-InstallNotesFile $notesTxt $profile
Copy-HelperScripts $InstallPath
Write-Ok "Wrote $configPs1"
Write-Ok "Wrote $configJs"
Write-Ok "Wrote $notesTxt"

# Also write next to installer (for USB / pre-install folder testing)
Write-LauncherConfigFile (Join-Path $scriptDir "xray-launcher-config.ps1") $profile

if ($BananaWebPath -and (Test-PathSafe $BananaWebPath)) {
    if ($Profile.primary_scan_root -and $Profile.primary_scan_root.Length -gt 8) {
        $webCfg = Join-Path $BananaWebPath "xray-pc-config.js"
        Write-BananaPcConfigFile $webCfg $profile
        Write-Ok "Updated Banana web config: $webCfg"
    } else {
        Write-Warn2 "Skipped web config — SCAN root not detected on this PC"
    }
} else {
    $guess = (Resolve-Path (Join-Path $scriptDir "..\..\") -ErrorAction SilentlyContinue)
    if ($guess -and (Test-PathSafe (Join-Path $guess "index.html")) -and $Profile.primary_scan_root -and $Profile.primary_scan_root.Length -gt 8) {
        $webCfg = Join-Path $guess "xray-pc-config.js"
        Write-BananaPcConfigFile $webCfg $profile
        Write-Ok "Updated Banana web config: $webCfg"
    } else {
        Write-Warn2 "Copy $configJs to your Banana folder as xray-pc-config.js"
    }
}

Write-Host ""
Write-Host "Install complete — role: $($profile.role)" -ForegroundColor Green
Write-Host "  Bridge:  http://127.0.0.1:$Port/status"
Write-Host "  Notes:   $notesTxt"
Write-Host ""
exit 0
