# Auto-generated by Carestream MCP Bridge installer ??2026-08-27 04:18
# PC role: xray-server on XRAY-MCP
$script:NntScanRootsOverride = @(
    "\\RECEPTION_MCP\IMAGE\SCAN",
)
$script:CarestreamBridgeRole = "xray-server"
$script:CarestreamBridgeHostname = "XRAY-MCP"
